#!/usr/bin/env fish

# Ask for file type
set file_type (echo -e "Document\nVideo\nImage" | bemenu -i -p "Select file type:")

# Handle file type selection
switch $file_type
    case Document
        # Ask for document name
        set search_term (echo "" | bemenu -i -p "Enter document name to search:")

        if test -n "$search_term"
            # Search for documents and pipe to bemenu for selection
            set selected_file (fd -i --type f -e pdf -e epub -e djvu "$search_term" / | \
                bemenu -i -l 15 -p "Select document:")

            if test -n "$selected_file"
                if test -f "$selected_file"
                    zathura "$selected_file" &
                else
                    notify-send Error "Document not found: $selected_file"
                end
            end
        end

    case Video
        # Ask for video name
        set search_term (echo "" | bemenu -i -p "Enter video name to search:")

        if test -n "$search_term"
            # Search for videos and pipe to bemenu for selection
            set selected_file (fd -i --type f -e mp4 -e mkv -e avi -e mov -e webm -e m4v -e flv "$search_term" / | \
                bemenu -i -l 15  "Select video:")

            if test -n "$selected_file"
                if test -f "$selected_file"
                    mpv "$selected_file" &
                else
                    notify-send Error "Video not found: $selected_file"
                end
            end
        end

    case Image
        # Ask for video name
        set search_term (echo "" | bemenu -i -p "Enter image name to search:")

        if test -n "$search_term"
            # Search for images and pipe to bemenu for selection
            set selected_file (fd --type f -e jpg -e png -e jpeg -e gif -e bmp -e tiff "$search_term" / | \
                bemenu -i -l 15 -p "Select image:") \

            if test -n "$selected_file"
                if test -f "$selected_file"
                    imv "$selected_file"
                else
                    notify-send Error "Image not found: $selected_file"
                end
            end
        end
end
