#!/usr/bin/env fish

# Ask for file type
set type (echo -e "Full\n\nMonitor\n\nSelection" | bemenu -i -p "Screenshot type: ")

# Handle file type selection
switch $type
    case "Full"
        hyprshot -m window -o ~/Desktop/

    case "Monitor"
        hyprshot -m output -o ~/Desktop/
	
    case "Selection"
        hyprshot -m region --raw -o ~/Desktop/ | swappy -f -
  
    case '*'
        notify-send "No screenshot type selected"
end
