#!/usr/bin/env fish

# Simple script to handle a DIY shutdown menu.
# Requirements:
# - dmenu

set chosen (echo -e "[Cancel]\nLogout\nShutdown\nReboot\n" | dmenu-wl -i -p "Choose an action:")

if test "$chosen" = "Logout"
	pkill -u (whoami)
  else if test "$chosen" = "Shutdown"
	shutdown now
else if test "$chosen" = "Reboot"
	shutdown -r
end
