#!/usr/bin/env fish

# Simple script to handle a DIY shutdown menu.
# Requirements:
# - dmenu

set chosen (echo -e "[Cancel] \nLogout \nShutdown \nReboot\n" | bemenu -i --fn monospace 16 -p "Choose an action:")

if test "$chosen" = "Logout"
	pkill -u (whoami)
  else if test "$chosen" = "Shutdown"
	sudo shutdown now
else if test "$chosen" = "Reboot"
	sudo shutdown -r
end
