#!/usr/bin/env fish

# Simple script to handle a DIY shutdown menu
# Requirements: bemenu, systemd

set options "[Cancel]\nLogout\nShutdown\nReboot"
set chosen (echo -e $options | bemenu -i -p "Power Menu:")

switch "$chosen"
    case "Logout"
         pkill -KILL -u $USER
	
    case "Shutdown"
        systemctl poweroff
        
    case "Reboot"
        systemctl reboot
        
    case '*'
        echo "Cancelled."
end
