#!/bin/bash

SECOND_MONITOR=$(hyprctl monitors -j | jq '.[1].name' | tr -d '"')

if [[ $(hyprctl activewindow | rg monitor | awk '{print $2}') -eq 0 ]]; then
	hyprctl dispatch "hl.dsp.window.move({ monitor = \"$SECOND_MONITOR\" })"
else
	hyprctl dispatch "hl.dsp.window.move({ monitor = \"eDP-1\" })"
fi
