[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[manager.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = [ "b", "D" ]
run = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"

[[manager.prepend_keymap]]
on = [ "g", "v" ]
run = "cd '~/Videos'"
desc = "Go to Videos folder" 

[[manager.prepend_keymap]]
on = [ "g", "w" ]
run = "cd '~/Documents/sports-cloud-webapp'"
desc = "Go to webapp folder" 

[[manager.prepend_keymap]]
on = [ "g", "u" ]
run = "cd '~/Documents/ui2'"
desc = "Go to ui2 folder" 

[[manager.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

[[manager.prepend_keymap]]
on = ["<C-t>"]
run = "shell swayimg --gallery"
desc = "Open current directory in swayimg gallery"

[[manager.prepend_keymap]]
on   = "M"
run  = "plugin mount"
desc = "Mount manager"

[[manager.prepend_keymap]]
on   = [ "'" ]
run  = "plugin first-non-directory"
desc = "Jumps to the first file"
