[mgr]
linemode = "size"
sort_dir_first = true
sort_reverse = true
show_permissions = true

[plugin]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/epub+zip",        run = "epub-preview" },
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
  { mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
  { url = "*.md",     run = 'faster-piper --rely-on-preloader' },
  { url = "*.tar*",   run = 'faster-piper --rely-on-preloader --format=url' },
  { url = "*.txt.gz", run = 'faster-piper --rely-on-preloader' },
]

prepend_preloaders = [
  { url = "*.md",     run = 'faster-piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dracula -- "$1"' },
  { url = "*.tar*",   run = 'faster-piper -- tar tf "$1"' },
  { url = "*.txt.gz", run = 'faster-piper -- gzip -dc "$1"' },
]
