[mgr]
linemode = "size"
sort_dir_first = true
sort_reverse = true
show_permissions = true

[opener]
epub = [
	{ run = 'foliate "$@"', orphan = true, desc = "Foliate" },
]

[open]
prepend_rules = [
	{ mime = "application/epub+zip", use = "epub" },
]

[plugin]
prepend_previewers = [
	# Archive previewer
	{ mime = "application/epub+zip",        run = "epub-preview" },
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
  { mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
  { url = "*.md",     run = 'faster-piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dracula -- "$1"' },
  { url = "*.tar*",   run = 'faster-piper --format=url -- tar tf "$1"' },
  { url = "*.txt.gz", run = 'faster-piper --rely-on-preloader' },
]

prepend_fetchers = [
 { id = "git", url = "*",  run = "git", group = "git" },
 { id = "git", url = "*/", run = "git", group = "git" },
]
