[Terminal]
source        = imaps://tasnimalamcse%40yahoo.com:sunorhktxtxuxeyr%40@imap.mail.yahoo.com:993
outgoing      = smtps://tasnimalamcse%40yahoo.com:sunorhktxtxuxeyr%40@smtp.mail.yahoo.com:465
default       = INBOX
from          = "Tasnim Alam" <tasnimalamcse@yahoo.com>
cache-headers = true
