#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

feh --bg-fill ~/Pictures/mountain.png &

bsp-layout set tall 1 &

picom --experimental-backends --config ~/.config/picom/picom.conf &

ibus-daemon -drxR &

nm-applet &

# make right menu key super
xmodmap -e "keycode 135=Super_R"

# make caps lock as home
xmodmap -e "keycode 66 = KP_Home"

# make home as caps lock
xmodmap -e "keycode 110 = Caps_Lock"

$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4

bspc config border_width 0
bspc config window_gap 6

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_padding 28

bspc rule -a Zathura desktop=^3 state=tiled follow=on
bspc rule -a Emacs desktop='^3' state=tiled follow=on
bspc rule -a Slack desktop='^4' state=floating follow=on
bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Zoom desktop='^4' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a URxvt:urxvt_keys_help state=floating

# Delete desktop when all client are disconnected
$HOME/.config/bspwm/delete-desktop.sh

# Gracefull delete
$HOME/.config/bspwm/graceful-delete.sh
