#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

feh --bg-fill ~/Downloads/blur_colorful_gradient_4k_hd_abstract-1920x1080.jpg &

picom --config ~/.config/picom/picom.conf &

$HOME/.config/polybar/launch.sh

bspc monitor -d  1 2 3 4 5 6 7 8 
 
bspc config border_width         0
bspc config window_gap           6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 28

bspc rule -a Zathura state=tiled state=fullscreen
bspc rule -a Emacs desktop='^3' state=tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zoom desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off

