#! /bin/sh

# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &

$HOME/.config/polybar/launch.sh

bspc monitor -d  1 2 3 4 5 6 7 8 
 
bspc config border_width         0
bspc config window_gap           6 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 28

bspc rule -a Zathura state=fullscreen
bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
